export const INDUSTRY_OPTIONS = [
    { value: 'Technology', label: 'Technology' },
    { value: 'Finance', label: 'Finance' },
    { value: 'Healthcare', label: 'Healthcare' },
    { value: 'Education', label: 'Education' },
    { value: 'Manufacturing', label: 'Manufacturing' },
    { value: 'Retail', label: 'Retail' },
    { value: 'Logistics', label: 'Logistics' },
    { value: 'Real Estate', label: 'Real Estate' },
    { value: 'Energy', label: 'Energy' },
    { value: 'Entertainment', label: 'Entertainment' },
    { value: 'Consulting', label: 'Consulting' },
    { value: 'Construction', label: 'Construction' },
    { value: 'Legal', label: 'Legal' },
    { value: 'Transportation', label: 'Transportation' },
    { value: 'Media', label: 'Media' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'Agriculture', label: 'Agriculture' },
    { value: 'Food & Beverage', label: 'Food & Beverage' },
    { value: 'Hospitality', label: 'Hospitality' },
    { value: 'Tourism', label: 'Tourism' },
    { value: 'Insurance', label: 'Insurance' },
    { value: 'Aviation', label: 'Aviation' },
    { value: 'Automotive', label: 'Automotive' },
    { value: 'Pharmaceutical', label: 'Pharmaceutical' },
    { value: 'Biotechnology', label: 'Biotechnology' },
    { value: 'Mining', label: 'Mining' },
    { value: 'Oil & Gas', label: 'Oil & Gas' },
    { value: 'Public Sector', label: 'Public Sector' },
    { value: 'Government', label: 'Government' },
    { value: 'Defense', label: 'Defense' },
    { value: 'Non-Profit', label: 'Non-Profit' },
    { value: 'NGO', label: 'NGO' },
    { value: 'Environmental Services', label: 'Environmental Services' },
    { value: 'Waste Management', label: 'Waste Management' },
    { value: 'Recycling', label: 'Recycling' },
    { value: 'Fashion', label: 'Fashion' },
    { value: 'Textiles', label: 'Textiles' },
    { value: 'Luxury Goods', label: 'Luxury Goods' },
    { value: 'Sports', label: 'Sports' },
    { value: 'Fitness & Wellness', label: 'Fitness & Wellness' },
    { value: 'Gaming', label: 'Gaming' },
    { value: 'E-commerce', label: 'E-commerce' },
    { value: 'Marketplace', label: 'Marketplace' },
    { value: 'FinTech', label: 'FinTech' },
    { value: 'EdTech', label: 'EdTech' },
    { value: 'HealthTech', label: 'HealthTech' },
    { value: 'PropTech', label: 'PropTech' },
    { value: 'TravelTech', label: 'TravelTech' },
    { value: 'Maritime', label: 'Maritime' },
];


export const SPECIALITY_OPTIONS = [
    { value: 'Web Development', label: 'Web Development' },
    { value: 'Mobile App Development', label: 'Mobile App Development' },
    { value: 'Frontend Development', label: 'Frontend Development' },
    { value: 'Backend Development', label: 'Backend Development' },
    { value: 'Full Stack Development', label: 'Full Stack Development' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'Cloud Computing', label: 'Cloud Computing' },
    { value: 'Internet of Things', label: 'Internet of Things' },
    { value: 'DevOps', label: 'DevOps' },
    { value: 'Site Reliability Engineering', label: 'Site Reliability Engineering' },
    { value: 'Data Science', label: 'Data Science' },
    { value: 'Data Engineering', label: 'Data Engineering' },
    { value: 'Machine Learning', label: 'Machine Learning' },
    { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
    { value: 'Business Intelligence', label: 'Business Intelligence' },
    { value: 'Digital Marketing', label: 'Digital Marketing' },
    { value: 'SEO', label: 'SEO' },
    { value: 'Content Marketing', label: 'Content Marketing' },
    { value: 'Social Media Marketing', label: 'Social Media Marketing' },
    { value: 'Performance Marketing', label: 'Performance Marketing' },
    { value: 'Product Management', label: 'Product Management' },
    { value: 'Project Management', label: 'Project Management' },
    { value: 'Program Management', label: 'Program Management' },
    { value: 'UI/UX Design', label: 'UI/UX Design' },
    { value: 'Graphic Design', label: 'Graphic Design' },
    { value: 'Motion Design', label: 'Motion Design' },
    { value: 'Game Development', label: 'Game Development' },
    { value: 'Quality Assurance', label: 'Quality Assurance' },
    { value: 'Software Testing', label: 'Software Testing' },
    { value: 'Cyber Forensics', label: 'Cyber Forensics' },
    { value: 'Network Engineering', label: 'Network Engineering' },
    { value: 'System Administration', label: 'System Administration' },
    { value: 'IT Support', label: 'IT Support' },
    { value: 'Blockchain Development', label: 'Blockchain Development' },
    { value: 'Smart Contract Development', label: 'Smart Contract Development' },
    { value: 'FinTech Solutions', label: 'FinTech Solutions' },
    { value: 'Investment Banking', label: 'Investment Banking' },
    { value: 'Financial Analysis', label: 'Financial Analysis' },
    { value: 'Risk Management', label: 'Risk Management' },
    { value: 'Accounting', label: 'Accounting' },
    { value: 'Auditing', label: 'Auditing' },
    { value: 'Human Resources', label: 'Human Resources' },
    { value: 'Talent Acquisition', label: 'Talent Acquisition' },
    { value: 'Learning & Development', label: 'Learning & Development' },
    { value: 'Supply Chain Management', label: 'Supply Chain Management' },
    { value: 'Procurement', label: 'Procurement' },
    { value: 'Operations Management', label: 'Operations Management' },
    { value: 'Logistics Optimization', label: 'Logistics Optimization' },
    { value: 'Renewable Energy Systems', label: 'Renewable Energy Systems' },
    { value: 'Sustainability Management', label: 'Sustainability Management' },
    { value: 'Compliance & Regulation', label: 'Compliance & Regulation' },
    { value: 'Legal Advisory', label: 'Legal Advisory' },
];
